name: Release

on:
  push:
    tags:
      - '*v*'

jobs:
  build:
    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: rsdo
          - os: windows-latest
            artifact_name: rsdo.exe
          - os: macos-latest
            artifact_name: rsdo

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build Release
      run: cargo build --release
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
