name: Release

on:
  push:
    tags:
      - '*v*'

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: rsdo
            asset_name: rsdo-linux
          - os: windows-latest
            artifact_name: rsdo.exe
            asset_name: rsdo-windows.exe
          - os: macos-latest
            artifact_name: rsdo
            asset_name: rsdo-macos

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build Release
      run: cargo build --release

    - name: Rename binary (Linux/macOS)
      if: runner.os != 'Windows'
      run: mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

    - name: Rename binary (Windows)
      if: runner.os == 'Windows'
      run: Rename-Item -Path target/release/${{ matrix.artifact_name }} -NewName ${{ matrix.asset_name }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
